### ISSUE TITLE
what is exec speed of AFL++ with qemu?

### ISSUE THREAD

**Issue by candou1611** [flankerhqd/vendor-android-cves#1]
Could you provide the version of vulnerable so and crash corpus for research?
BTW, what is exec speed of AFL++ with qemu?
Thanks

**Comment by flankerhqd** [comment]
Hello:
The relevant crashing samples are in their respective directories, such as https://github.com/flankerhqd/vendor-android-cves/tree/master/snotes-spi-fuzzing/spisamples/triaged_spi and https://github.com/flankerhqd/vendor-android-cves/tree/master/dng-fuzzing/samples.

The vulnerable so can be extracted from old versions of Samsung firmware (before security patch applies), you can get them from https://www.sammobile.com/samsung/galaxy-a70/firmware/, for example https://www.sammobile.com/samsung/galaxy-a70/firmware/SM-A7050/CHC/download/A7050ZCU5ATA2/317400/ should be a vulnerable version. (You can use SamFirm to download it). Old version of galaxy notes can be found at apkmirror (also before the patch applies, i.e. before 2021.5)

For the exec speed, it's about ~200 per core on a 56-core workstation, with a total speed of 11000+. So it's somehow acceptable.
