### ISSUE TITLE
Can you add a LICENSE file?

### ISSUE THREAD

**Issue by BLuFeNiX** [flankerhqd/vendor-android-cves#2]
Hi,

I am interested in forking some of the code in this repo, and I would like to respect your work and provide appropriate credit.

Would you care to provide a LICENSE file for this repo?

Thanks!

**Comment by flankerhqd** [comment]
Hi:

Thanks for reaching out. The relevant license has been added.

**Comment by BLuFeNiX** [comment]
Thank you so much for the quick reply!
